keyconfig_data = \
[("Screen",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.animation_step", {"type": 'TIMER0', "value": 'ANY', "any": True}, None),
    ("screen.region_blend", {"type": 'TIMERREGION', "value": 'ANY', "any": True}, None),
    ("screen.screen_full_area", {"type": 'SPACE', "value": 'PRESS', "ctrl": True}, None),
    ("screen.screen_full_area",
     {"type": 'SPACE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("use_hide_panels", True),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.workspace_cycle",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.workspace_cycle",
     {"type": 'PAGE_UP', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.region_quadview", {"type": 'Q', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("screen.repeat_last", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("file.execute", {"type": 'RET', "value": 'PRESS'}, None),
    ("file.execute", {"type": 'NUMPAD_ENTER', "value": 'PRESS'}, None),
    ("file.cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("ed.undo", {"type": 'Z', "value": 'PRESS', "ctrl": True}, None),
    ("ed.redo", {"type": 'Z', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("render.render",
     {"type": 'F12', "value": 'PRESS'},
     {"properties":
      [("use_viewport", True),
       ],
      },
     ),
    ("render.render",
     {"type": 'F12', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("animation", True),
       ("use_viewport", True),
       ],
      },
     ),
    ("render.view_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("render.view_show", {"type": 'F11', "value": 'PRESS'}, None),
    ("render.play_rendered_anim", {"type": 'F11', "value": 'PRESS', "ctrl": True}, None),
    ("ed.undo", {"type": 'Z', "value": 'PRESS', "oskey": True}, None),
    ("ed.redo", {"type": 'Z', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("ed.undo_history", {"type": 'Z', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("screen.userpref_show", {"type": 'COMMA', "value": 'PRESS', "oskey": True}, None),
    ("screen.fast_preview", {"type": 'SPACE', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Frames",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.frame_offset",
     {"type": 'LEFT_ARROW', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'RIGHT_ARROW', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("end", True),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("end", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'UP_ARROW', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'DOWN_ARROW', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_LAST', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_FIRST', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.animation_play",
     {"type": 'SPACE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("screen.animation_play",
     {"type": 'SPACE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("reverse", True),
       ],
      },
     ),
    ("screen.animation_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("screen.animation_cancel", {"type": 'MEDIA_STOP', "value": 'PRESS'}, None),
    ("screen.frame_offset",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ],
   },
  ),
 ("Outliner",
  {"space_type": 'OUTLINER', "region_type": 'WINDOW'},
  {"items":
   [("outliner.highlight_update", {"type": 'MOUSEMOVE', "value": 'ANY', "any": True}, None),
    ("outliner.item_rename", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("extend", False),
       ("recursive", False),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("recursive", False),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("extend", False),
       ("recursive", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("recursive", True),
       ],
      },
     ),
    ("outliner.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("outliner.item_openclose",
     {"type": 'RET', "value": 'PRESS'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'RET', "value": 'PRESS', "shift": True},
     {"properties":
      [("all", True),
       ],
      },
     ),
    ("outliner.item_rename", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.operation", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("outliner.item_drag_drop", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("outliner.item_drag_drop", {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True}, None),
    ("outliner.show_hierarchy", {"type": 'HOME', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'PERIOD', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("outliner.scroll_page",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("up", False),
       ],
      },
     ),
    ("outliner.scroll_page",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("up", True),
       ],
      },
     ),
    ("outliner.show_one_level", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("outliner.show_one_level",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("open", False),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("outliner.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("outliner.expanded_toggle", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("outliner.keyingset_add_selected", {"type": 'K', "value": 'PRESS'}, None),
    ("outliner.keyingset_remove_selected", {"type": 'K', "value": 'PRESS', "alt": True}, None),
    ("anim.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("outliner.drivers_add_selected", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.drivers_delete_selected", {"type": 'D', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("outliner.collection_new", {"type": 'C', "value": 'PRESS'}, None),
    ("outliner.collection_delete", {"type": 'X', "value": 'PRESS'}, None),
    ("outliner.collection_delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("outliner.collection_exclude_set", {"type": 'E', "value": 'PRESS'}, None),
    ("outliner.collection_exclude_clear", {"type": 'E', "value": 'PRESS', "alt": True}, None),
    ("object.hide_view_clear",
     {"type": 'H', "value": 'PRESS', "alt": True},
     {"properties":
      [("select", False),
       ],
      },
     ),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Markers",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("marker.add", {"type": 'M', "value": 'PRESS'}, None),
    ("marker.move", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("marker.duplicate", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("marker.select", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("marker.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("marker.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("extend", False),
       ("camera", True),
       ],
      },
     ),
    ("marker.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("camera", True),
       ],
      },
     ),
    ("marker.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("marker.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("marker.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("marker.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("marker.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("marker.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("marker.rename", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("marker.move", {"type": 'G', "value": 'PRESS'}, None),
    ("marker.camera_bind", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ("Dopesheet",
  {"space_type": 'DOPESHEET_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ("column", False),
       ("channel", False),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ("column", True),
       ("channel", False),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ("column", False),
       ("channel", False),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("column", True),
       ("channel", False),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("column", False),
       ("channel", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ("column", False),
       ("channel", True),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ("extend", False),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ("extend", True),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'LEFT'),
       ("extend", False),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'RIGHT'),
       ("extend", False),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("action.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("axis_range", False),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'B', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis_range", True),
       ],
      },
     ),
    ("action.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("action.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("action.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("mode", 'KEYS'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'CFRA'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'MARKERS_COLUMN'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MARKERS_BETWEEN'),
       ],
      },
     ),
    ("action.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("action.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("action.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("action.frame_jump", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'DOPESHEET_MT_snap_pie'),
       ],
      },
     ),
    ("action.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("action.handle_type", {"type": 'V', "value": 'PRESS'}, None),
    ("action.interpolation_type", {"type": 'T', "value": 'PRESS'}, None),
    ("action.extrapolation_type", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("action.keyframe_type", {"type": 'R', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_specials'),
       ],
      },
     ),
    ("action.sample", {"type": 'O', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_delete'),
       ],
      },
     ),
    ("action.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("action.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("action.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("action.paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("action.paste",
     {"type": 'V', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("flipped", True),
       ],
      },
     ),
    ("action.previewrange_set", {"type": 'P', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("action.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("action.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("action.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("action.view_frame", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("anim.channels_editable_toggle", {"type": 'TAB', "value": 'PRESS'}, None),
    ("anim.channels_find", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("transform.transform",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_TRANSLATE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("mode", 'TIME_TRANSLATE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_EXTEND'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_SCALE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'TIME_SLIDE'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_action'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("marker.add", {"type": 'M', "value": 'PRESS'}, None),
    ("marker.rename", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("action.copy", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("action.paste", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ("action.paste",
     {"type": 'V', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("flipped", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Edit Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.interpolate", {"type": 'E', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("gpencil.interpolate_sequence", {"type": 'E', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("gpencil.select", {"type": 'LEFTMOUSE', "value": 'CLICK'}, None),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("gpencil.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("gpencil.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("gpencil.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_alternate", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_gpencil_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_gpencil_delete'),
       ],
      },
     ),
    ("gpencil.dissolve", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.dissolve", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_gpencil_edit_specials'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'P', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_separate'),
       ],
      },
     ),
    ("gpencil.stroke_split", {"type": 'V', "value": 'PRESS'}, None),
    ("gpencil.stroke_join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.stroke_join",
     {"type": 'J', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'JOINCOPY'),
       ],
      },
     ),
    ("gpencil.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'GPENCIL_MT_snap'),
       ],
      },
     ),
    ("gpencil.convert", {"type": 'C', "value": 'PRESS', "alt": True}, None),
    ("gpencil.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("gpencil.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("gpencil.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("gpencil.selection_opacity_toggle", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ("gpencil.layer_isolate", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS'}, None),
    ("gpencil.move_to_layer", {"type": 'M', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'GPENCIL_SHRINKFATTEN'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'CONNECTED'),
       ],
      },
     ),
    ("object.gpencil_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'GPENCIL_MT_gpencil_vertex_group'),
       ],
      },
     ),
    ("gpencil.editmode_toggle", {"type": 'TAB', "value": 'PRESS'}, None),
    ("gpencil.selectmode_toggle",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("mode", 0),
       ],
      },
     ),
    ("gpencil.selectmode_toggle",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("mode", 1),
       ],
      },
     ),
    ("gpencil.copy", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("gpencil.paste", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ],
   },
  ),
 ("Grease Pencil Stroke Sculpt Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("gpencil.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("gpencil.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("gpencil.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_alternate", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.sculpt_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ("gpencil.sculpt_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ("gpencil.sculpt_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_sculpt.brush.strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_sculpt.brush.size'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_gpencil_sculpt_specials'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ],
   },
  ),
 ("Face Mask",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("paint.face_select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("paint.face_select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("paint.face_select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("paint.face_select_hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("paint.face_select_hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("paint.face_select_reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("paint.face_select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("paint.face_select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("paint.face_select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Weight Paint Vertex Selection",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("paint.vert_select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("paint.vert_select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("paint.vert_select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Pose",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("object.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_add'),
       ],
      },
     ),
    ("pose.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("pose.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("pose.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_pose_apply'),
       ],
      },
     ),
    ("pose.rot_clear", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("pose.loc_clear", {"type": 'G', "value": 'PRESS', "alt": True}, None),
    ("pose.scale_clear", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("pose.quaternions_flip", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("pose.rotation_mode_set", {"type": 'R', "value": 'PRESS', "ctrl": True}, None),
    ("pose.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("pose.paste",
     {"type": 'V', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("flipped", False),
       ],
      },
     ),
    ("pose.paste",
     {"type": 'V', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("flipped", True),
       ],
      },
     ),
    ("pose.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("pose.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("pose.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("pose.select_parent", {"type": 'P', "value": 'PRESS', "shift": True}, None),
    ("pose.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("pose.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("pose.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("pose.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("pose.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("pose.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("pose.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("pose.constraint_add_with_targets", {"type": 'C', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("pose.constraints_clear", {"type": 'C', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("pose.ik_add", {"type": 'I', "value": 'PRESS', "shift": True}, None),
    ("pose.ik_clear", {"type": 'I', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_pose_group'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_toggle'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_enable'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_disable'),
       ],
      },
     ),
    ("armature.layers_show_all", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("armature.armature_layers", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("pose.bone_layers", {"type": 'M', "value": 'PRESS'}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'BONE_SIZE'),
       ],
      },
     ),
    ("anim.keyframe_insert_menu", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete_v3d", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("anim.keying_set_active_set", {"type": 'I', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("poselib.browse_interactive", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("poselib.pose_add", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("poselib.pose_remove", {"type": 'L', "value": 'PRESS', "alt": True}, None),
    ("poselib.pose_rename", {"type": 'L', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("pose.push", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("pose.relax", {"type": 'E', "value": 'PRESS', "alt": True}, None),
    ("pose.breakdown", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pose_specials'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'P', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_pose_propagate'),
       ],
      },
     ),
    ("pose.copy", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("pose.paste",
     {"type": 'V', "value": 'PRESS', "oskey": True},
     {"properties":
      [("flipped", False),
       ],
      },
     ),
    ("pose.paste",
     {"type": 'V', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("flipped", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Object Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit_objects'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("object.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("object.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.select_linked", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("object.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("object.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("object.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("object.location_clear",
     {"type": 'G', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.rotation_clear",
     {"type": 'R', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.scale_clear",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ("confirm", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ("confirm", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_add'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_object_apply'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_make_links'),
       ],
      },
     ),
    ("object.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("object.duplicate_move_linked", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("object.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("anim.keyframe_insert_menu", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete_v3d", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("anim.keying_set_active_set", {"type": 'I', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.create", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("collection.objects_remove", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("collection.objects_remove_all", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.objects_add_active", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("collection.objects_remove_active", {"type": 'G', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_object_specials'),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("object.hide_view_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("object.hide_collection", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 1),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 2),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 3),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 4),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 5),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 6),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 7),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 8),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 9),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 10),
       ],
      },
     ),
    ],
   },
  ),
 ("Curve",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_curve_add'),
       ],
      },
     ),
    ("curve.handle_type_set", {"type": 'V', "value": 'PRESS'}, None),
    ("curve.vertex_add", {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("curve.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("curve.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("curve.select_row", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("curve.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("curve.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("curve.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("curve.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("curve.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("curve.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("curve.shortest_path_pick", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("curve.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("curve.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("curve.extrude_move", {"type": 'E', "value": 'PRESS'}, None),
    ("curve.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("curve.make_segment", {"type": 'F', "value": 'PRESS'}, None),
    ("curve.cyclic_toggle", {"type": 'C', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_delete'),
       ],
      },
     ),
    ("curve.dissolve_verts", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("curve.dissolve_verts", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("curve.tilt_clear", {"type": 'T', "value": 'PRESS', "alt": True}, None),
    ("transform.tilt", {"type": 'T', "value": 'PRESS', "ctrl": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'CURVE_SHRINKFATTEN'),
       ],
      },
     ),
    ("curve.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("curve.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("curve.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("curve.normals_make_consistent", {"type": 'N', "value": 'PRESS', "shift": True}, None),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_specials'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'CONNECTED'),
       ],
      },
     ),
    ],
   },
  ),
 ("Mesh",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("mesh.loopcut_slide",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.offset_edge_loops_slide",
     {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.inset", {"type": 'I', "value": 'PRESS'}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("vertex_only", False),
       ],
      },
     ),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("vertex_only", True),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK', "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", True),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mesh.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_similar'),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mesh.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True},
     {"properties":
      [("inside", False),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("view3d.edit_mesh_extrude_move_normal", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_extrude'),
       ],
      },
     ),
    ("transform.edge_crease", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("mesh.fill", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.tris_convert_to_quads", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", True),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_edge_move", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("mesh.merge", {"type": 'M', "value": 'PRESS', "alt": True}, None),
    ("transform.shrink_fatten", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("mesh.edge_face_add", {"type": 'F', "value": 'PRESS'}, None),
    ("mesh.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_mesh_add'),
       ],
      },
     ),
    ("mesh.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("mesh.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("mesh.vert_connect_path", {"type": 'J', "value": 'PRESS'}, None),
    ("mesh.point_normals", {"type": 'L', "value": 'PRESS', "alt": True}, None),
    ("transform.vert_slide", {"type": 'V', "value": 'PRESS', "shift": True}, None),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("use_occlude_geometry", True),
       ("only_selected", False),
       ],
      },
     ),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_specials'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_faces'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_edges'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_vertices'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_uv_map'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_vertex_group'),
       ],
      },
     ),
    ("object.vertex_group_remove_from", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'CONNECTED'),
       ],
      },
     ),
    ],
   },
  ),
 ("Armature",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("armature.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("armature.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("armature.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("armature.align",
     {"type": 'A', "value": 'PRESS', "ctrl": True, "alt": True},
     {    "active":False,
      },
     ),
    ("armature.calculate_roll", {"type": 'N', "value": 'PRESS', "shift": True}, None),
    ("armature.roll_clear", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("armature.switch_direction", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("armature.bone_primitive_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("armature.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("armature.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("armature.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("armature.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("armature.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("armature.select_mirror",
     {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("armature.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("armature.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("armature.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("armature.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("armature.shortest_path_pick", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_armature_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_armature_delete'),
       ],
      },
     ),
    ("armature.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("armature.dissolve", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("armature.dissolve", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("armature.extrude_move", {"type": 'E', "value": 'PRESS'}, None),
    ("armature.extrude_forked", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("armature.click_extrude", {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("armature.fill", {"type": 'F', "value": 'PRESS'}, None),
    ("armature.merge", {"type": 'M', "value": 'PRESS', "alt": True}, None),
    ("armature.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("armature.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_toggle'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_enable'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_disable'),
       ],
      },
     ),
    ("armature.layers_show_all", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("armature.armature_layers", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("armature.bone_layers", {"type": 'M', "value": 'PRESS'}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'BONE_SIZE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'BONE_ENVELOPE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'BONE_ROLL'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_armature_specials'),
       ],
      },
     ),
    ],
   },
  ),
 ("Metaball",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("object.metaball_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("mball.reveal_metaelems", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mball.hide_metaelems",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mball.hide_metaelems",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mball.delete_metaelems", {"type": 'X', "value": 'PRESS'}, None),
    ("mball.delete_metaelems", {"type": 'DEL', "value": 'PRESS'}, None),
    ("mball.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("mball.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("mball.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("mball.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mball.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'CONNECTED'),
       ],
      },
     ),
    ],
   },
  ),
 ("Lattice",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("lattice.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("lattice.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("lattice.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("lattice.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("lattice.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("lattice.flip", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ],
   },
  ),
 ("Particle",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("particle.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("particle.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
    "active":False,
      },
     ),
    ("particle.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("particle.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("particle.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("particle.select_linked",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("particle.select_linked",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("particle.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("particle.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("particle.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("particle.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("particle.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("particle.brush_edit", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("particle.brush_edit", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.particle_edit.brush.size'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.particle_edit.brush.strength'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_particle_specials'),
       ],
      },
     ),
    ("particle.weight_set", {"type": 'K', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ],
   },
  ),
 ("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("view3d.cursor3d", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("transform.translate",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True},
     {"properties":
      [("cursor_transform", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("view3d.localview", {"type": 'NUMPAD_SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'SLASH', "value": 'PRESS'}, None),
    ("view3d.localview_remove_from", {"type": 'M', "value": 'PRESS'}, None),
    ("view3d.rotate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view3d.move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view3d.zoom", {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("view3d.dolly", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.view_selected",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.rotate", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view3d.rotate", {"type": 'MOUSEROTATE', "value": 'ANY'}, None),
    ("view3d.move", {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True}, None),
    ("view3d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view3d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_view_pie'),
       ],
      },
     ),
    ("view3d.navigate", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_camera", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'NUMPAD_5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'NORTH', "alt": True},
     {"properties":
      [("type", 'TOP'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'SOUTH', "alt": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'EAST', "alt": True},
     {"properties":
      [("type", 'RIGHT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'WEST', "alt": True},
     {"properties":
      [("type", 'LEFT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_center_pick", {"type": 'MIDDLEMOUSE', "value": 'CLICK', "alt": True}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.select_or_deselect_all", {"type": 'LEFTMOUSE', "value": 'CLICK'}, None),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("center", True),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ("center", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_PT_snapping'),
       ("keep_open", False),
       ],
      },
     ),
    ("object.transform_axis_target", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo_tool'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo_tool'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_shading_pie'),
       ],
      },
     ),
    ("view3d.toggle_shading",
     {"type": 'Z', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'WIREFRAME'),
       ],
      },
     ),
    ("view3d.toggle_xray", {"type": 'Z', "value": 'PRESS', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.tool_set_by_name",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'Select Box'),
       ("cycle", True),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("angle", 0.05),
       ("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("angle", 0.05),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.aim_at_selected", {"type": 'NONE', "value": 'PRESS'}, None),
    ("view3d.aim_at_selected", {"type": 'A', "value": 'PRESS', "alt": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(os.path.splitext(os.path.basename(__file__))[0], keyconfig_data)
